### ISSUE TITLE
없어진 화면 살리기

### ISSUE THREAD

**Issue by riflockle7** [duckie-team/duckie-android#126]
아키텍처 리펙터링 하면서 죽음을 맞이한 화면들 다시 살리기
- [ ] 설정 화면 (https://github.com/duckie-team/duckie-android/pull/53)
- [ ] 알림 화면 (https://github.com/duckie-team/duckie-android/pull/54)

**Comment by jisungbin** [comment]
온보딩 연결 끝내고 제가 담당할까요?

**Comment by riflockle7** [comment]
이건 이번 스프린트 작업이 아니어서, 현재 스프린트의 다른 기능을 먼저 봐주시면 좋을 것 같습니다
이거는 일단 리마인드용으로 만들어 놨었습니다.

**Comment by jisungbin** [comment]
> 이건 이번 스프린트 작업이 아니어서, 현재 스프린트의 다른 기능을 먼저 봐주시면 좋을 것 같습니다 이거는 일단 리마인드용으로 만들어 놨었습니다.

감사합니다.
