### ISSUE TITLE
추후 개선할 아키텍처 내용 정리

### ISSUE THREAD

**Issue by riflockle7** [duckie-team/duckie-android#128]
## 상우

- [ ] DataSource - local, remote 등을 자유롭게 주입할 수 있도록 처리
- [ ] Test 에서 Real Server 테스트

## 성빈

- [ ] 오버엔지니어링 제거
- [ ] 조기 최적화 제거

**Comment by jisungbin** [comment]
real server 테스트는 없애려고 합니다. 빌드 속도도 그렇고, 매번 비용 나가는 문제도 그렇고 영 아니여서요.

**Comment by jisungbin** [comment]
datasource 는 의미가 없어 보이지만 도입하신다면 따르겠습니다. 다양한 관점을 경험해 보면 좋으니깐요.

**Comment by riflockle7** [comment]
> 빌드 속도도 그렇고, 매번 비용 나가는 문제도 그렇고 영 아니여서요. 

기본적으로는 꺼두고, unitTest 실행할때만 토클처럼 잠깐 켰다 끄는 걸 생각했었어요
API ping 을 안스에서 하는 방법으로 생각하시면 될 듯

**Comment by jisungbin** [comment]
> 기본적으로는 꺼두고, 작업하면서 토글처럼 잠깐 켰다 끄는 걸 생각했었어요

postman 으로 대체가 되지 않나요? postman 이 있는데 굳이 직접 unit test 에 실서버 테스트를 작성하는 건 개발자 경험 낭비라고 생각합니다.
