### ISSUE TITLE
HttpClient Fuel 로 마이그레이션

### ISSUE THREAD

**Issue by jisungbin** [duckie-team/duckie-android#180]
ktor-client 을 사용하면 min-sdk 가 24 로 상향됨
ktor-client 의 대안으로 Fuel 를 사용하고자 함

**Comment by jisungbin** [comment]
@riflockle7 MVP 출시 이후에 진행하겠습니다.

**Comment by jisungbin** [comment]
아니다 그냥 제 다음 작업부터 천천히 적용할게요

**Comment by riflockle7** [comment]
어 이건 왜 닫혔을까요? x 2
