### ISSUE TITLE
Jackson -> Moshi 마이그레이션

### ISSUE THREAD

**Issue by jisungbin** [duckie-team/duckie-android#184]
현재 덕키 프로젝트는 Jackson 의 이점을 못 누리고 있음
Jackson 의 이점을 누리기 위해선 덕키가 대형 서비스로 발전해야 함
따라서 현재 환경에선 더 적합한 Moshi 로 마이그레이션을 진행하고자 함

**Comment by riflockle7** [comment]
어 직접 비교를 해봐야하긴 하겠지만, 현재 내용으로만 보자면 
결국은 Jackson 을 사용해야하는 게 좋지 않을까요?

**Comment by jisungbin** [comment]
> 어 직접 비교를 해봐야하긴 하겠지만, 현재 내용으로만 보자면 결국은 Jackson 을 사용해야하는 게 좋지 않을까요?

jackson 의 이점을 현재 하나도 누리지 못 하고 있습니다. 그리고 min-sdk 에도 제약이 걸립니다.

**Comment by riflockle7** [comment]
> Jackson 의 이점을 누리기 위해선 덕키가 대형 서비스로 발전해야 함

말씀하신 `대형 서비스`의 의미를 제가 잘못 생각했었네요
결국 돌아올 것을 고려하고 있으시다면, 그로 인한 2중작업이 되는 걸 막고 싶었습니다

하지만 왔다갔다하면서 다양한 직렬화 라이브러리를 사용해보고 거기서 배우는 바도 있을 듯 하네요
네네 추후 적용하시죠
