### ISSUE TITLE
Splash 화면에서 온보딩 화면으로 진입 불가

### ISSUE THREAD

**Issue by riflockle7** [duckie-team/duckie-android#260]
https://www.notion.so/jisungbin/Splash-c338784011c347f28fbd7c2807876831?pvs=4

**Comment by riflockle7** [comment]
제가 처리해볼게요

https://sungbinland.slack.com/archives/C03CM18M529/p1677338692346889?thread_ts=1677337434.103489&cid=C03CM18M529 부터 대화 참고할 것

**Comment by jisungbin** [comment]
# :deabak:
