### ISSUE TITLE
CI 개선

### ISSUE THREAD

**Issue by riflockle7** [duckie-team/duckie-android#265]
- [x] ./gradlew build${variant} 가 일부 검사하지 않는 것도 있음 (ex. detekt)
        하지만 build 실행으로 해결하고 싶지 않아, CI 체크를 쪼갤 예정
- [x] yaml 코드 최신화

**Comment by riflockle7** [comment]
@jisungbin 혹시 앱내에서 `binary-compatibility` 도 할 수 있는 상태인가요?
[이거](https://proandroiddev.com/android-library-compatibility-and-public-api-management-with-binary-compatibility-validator-971762957594) 확인해봤는데 관련 gradlew 명령어가 동작을 안해서 이게 아닌가 싶기도 하네요 🤔

**Comment by jisungbin** [comment]
오잉 모르겠어요

**Comment by riflockle7** [comment]
엌ㅋㅋ 적혀있길래 여쭤봤었는데 ㅋㅋㅋ 음 없다면 저건 신경 안쓸게요 🙏

**Comment by jisungbin** [comment]
아 그거라면 https://github.com/Kotlin/binary-compatibility-validator 이거에요
