### ISSUE TITLE
android-ci 그레이들 캐싱 방식 롤백 필요

### ISSUE THREAD

**Issue by jisungbin** [duckie-team/duckie-android#281]
https://github.com/actions/setup-java#caching-packages-dependencies

내부적으로 cache action을 사용합니다. third-party 캐싱보다 first-party 캐싱이 더 좋아 보입니다.

**Comment by riflockle7** [comment]
https://github.com/gradle/gradle-build-action (과거) vs https://github.com/actions/setup-java#caching-packages-dependencies (현재) 일까요?

**Comment by jisungbin** [comment]
네

**Comment by riflockle7** [comment]
![image](https://user-images.githubusercontent.com/13694046/222945535-07ceb55b-ba79-4776-b356-f30d6a0d9a2d.png)

이 부분을 보면 확실히 그런 것 같네요

**Comment by jisungbin** [comment]
네
