### ISSUE TITLE
println 전부 제거하기

### ISSUE THREAD

**Issue by riflockle7** [duckie-team/duckie-android#449]
예전부터 생각하던 내용인데, 도로님이 이야기해주시면서 기억남
로그로 다 내용이 나오고, 심지어 release 에서도 나오기 때문에 제거 반드시 필요

**Comment by EvergreenTree97** [comment]
Timber를 사용하는건 어떨까요?
- Debug에서마
https://github.com/JakeWharton/timber

**Comment by goddoro** [comment]
그리고 println은 메인스레드에 직접 작동해서 앱 성능에도 좀 영향을 미치지 않나여?
