### ISSUE TITLE
덕키 앱 패키지 구조 변경

### ISSUE THREAD

**Issue by riflockle7** [duckie-team/duckie-android#496]
history & ref
- https://duckie-team.slack.com/archives/C054F0B725T/p1683375247752349
- https://github.com/android/nowinandroid/blob/88b9e023d05f297c04955f70c1a700288e03b[%E2%80%A6]les/apps/nowinandroid/sync/services/SyncNotificationsService.kt

---
# 옮김 처리 작업

- [x] build-logic, buildSrc : 성빈님
- [x] data:
- [ ] di: 없애도 된다고 들어서 정리 필요
- [x] documents: 레거시, 필요 없으면 제거
- [x] feature-datastore: 피처가 아닌 것 같다
- [x] feature-messaging: 푸시 관련 
        (피처 맞는 것 같음 → sync, noti 같이 우리만의 이름으로 만들기)
- [x] feature-photopicker: shared 에 어울리는 듯
- [x] featrue-ui 시리즈: ui 관련
        feature 이름 그대로 사용하고, 해당 디렉터리로 묶어서 사용하기
        종류
        - feature-ui-create-problem
        - feature-ui-detail
        - feature-ui-exam-result
        - feature-ui-friends
        - feature-ui-home
        - feature-ui-notification
        - feature-ui-onboard
        - feature-ui-profile
        - feature-ui-search
        - feature-ui-setting
        - feature-ui-solve-problem
        - feature-ui-start-exam
        - feature-ui-tag-edit  
- [x] shared-ui-compose
- [x] util-android
- [x] util-kotlin
- [x] util-compose
- [x] util-exception-handling
- [x] util-ui

---

# 각 피처별 특이사항

feature-ui-____
- [x] feature-ui- 네이밍 없앰

util 및 shared 시리즈들
- [x] common 이라는 디렉터리 하에 위의 모듈들을 넣기
- [x] util-android, util-ui 합치기
- [ ] common
  - [ ] [compose (구 util-compose + 구 shared-ui-compose)](https://github.com/duckie-team/duckie-android/issues/496#issuecomment-1555967993)
  - [x] android (구 util-android, 구 util-ui, 구 exception-handling 를 합침)
  - [x] kotlin (구 util-kotlin)

**Comment by EvergreenTree97** [comment]
그러고보니

feature-messaging: 푸시 관련
(피처 맞는 것 같음 → sync, noti 같이 우리만의 이름으로 만들기)

이거 sync로 결정이 났었을까요

**Comment by riflockle7** [comment]
> 그러고보니
> 
> feature-messaging: 푸시 관련
> (피처 맞는 것 같음 → sync, noti 같이 우리만의 이름으로 만들기)
> 이거 sync로 결정이 났었을까요

저도 잘 모르겠네요... 일단은 sync 사례 찾아볼게요

**Comment by riflockle7** [comment]
사실 그거 말고도 애매한 스탠스가 있어서... 
ex. feature-photopicker: shared 에 어울리는 듯
일단은 제 생각해로 해볼게요

**Comment by riflockle7** [comment]
정리
![image](https://github.com/duckie-team/duckie-android/assets/13694046/54539839-cb04-4f3c-a1e9-c61cf1465c9d)

**Comment by riflockle7** [comment]
# 각 피처별 특이사항

feature-ui-____
- feature-ui- 네이밍 없앰

**Comment by riflockle7** [comment]
패키지 모듈 변경 방법 (Android Studio Giraffe 기준)
1. Refactor -> Rename 을 실행한 뒤, Rename module 을 선택한다.
  ![image](https://github.com/duckie-team/duckie-android/assets/13694046/43853d87-8967-4ec9-9d31-5a5f7c68395b)
2. 원하는 이름으로 변경한다.
  ![image](https://github.com/duckie-team/duckie-android/assets/13694046/6ce6407b-717c-49e0-a8cb-fa7462560e0f)
  변경 후 Android Studio 내부에서 동작이 있고 에러가 발생할 것이다. 일단은 무시한다.
3. 드래그 하여 옮겨준다.
   ![image](https://github.com/duckie-team/duckie-android/assets/13694046/8356688b-ea11-4f9b-8375-66124cbaf8d4)
4. 2번 과정을 통해 `settings.gradle.kts` 에 변경된 이름이 반영되었을 것이다.
   옮긴 디렉터리에 맞춰 include 내 projectPath 명을 변경해준다.
   ![image](https://github.com/duckie-team/duckie-android/assets/13694046/64428ba5-caa0-4bb0-88fd-b7ec31ad259d)
5. 변경된 내용에 맞춰 아래 내용들을 변경해준다.
  - 변경된 모듈 build.gradle.kts 내 namespace
  - 해당 모듈 사용처 (주로 implementation)
  - 모듈 내 코드 import
    - Android Studio 내에서 drag & move 형태로 진행하면 쉽게 변경할 수 있다
    디렉터리 이름 변경 관련 tip
    2가지가 있다 입맛에 맞춰 선택하면 된다.
     1. 새로운 디렉터리를 만들어준 뒤, 옮겨주는 방식
       - 개인적으로는 추천
       - refactor -> rename 으로 변경 시, Android Studio 내에서 이름이 같은 다른 모듈도 변경하려함
         이 때 잘못 선택하면 ctrl + z 도 안 통하는 결과를 얻을 수 있으므로 주의
       - `Designed and developed by Duckie Team, 2022` 주석이 자동 추가되는 경우가 있어 이건 주의

     2. 모듈 기준으로 find in files (cmd + shift + f) 에서 replace 로 변경

**Comment by riflockle7** [comment]
패키지 조정하면서 보니 util 과 ui 를 구분 시킬 필요도 없을 것 같습니다.
common 내 android 와 통일성도 지켜야 하구요?
그래서 아래와 같이 진행하려 합니다

## AS-IS

- [ ] common
  - [ ] compose
    - [ ] ui (구 shared-ui-compose)
    - [ ] util (구 util-compose)

## TO-BE

- [ ] common
  - [ ] compose (구 util-compose + 구 shared-ui-compose)
