### ISSUE TITLE
DI 방식 변경

### ISSUE THREAD

**Issue by jisungbin** [duckie-team/duckie-android#51]
## Domain

```groovy
implementation "javax.inject:javax.inject:1"
```

위처럼 `javax.inject` 만 implementation 하면, domain 레이어가 hilt 를 알지 못해도 hilt 의 `@Inject` 를 받을 수 있음

```kotlin
class CheckCurrentUserUseCase @Inject constructor(
    private val repository: LoginRepository
) {
    operator fun invoke(uid: String): Flow<Boolean> = repository.checkCurrentUser(uid)
}
```

이를 응용하여 domain 레이어의 usecase 에서 위와 같이 쓸 수 있다.

## Data

data 레이어에서는 hilt 전체를 implementation 하여 provides 가 필요함

## Reference

- https://github.com/boostcampwm-2022/android06-mogle
- https://github.com/boostcampwm-2022/android01-UCMC

**Comment by EvergreenTree97** [comment]
혹시 관련 예제 소스가 있을까요? Hilt Compiler 의존성 같은 것들을 추가하지 않아도 잘 작동할지 궁금해서요!

**Comment by jisungbin** [comment]
@EvergreenTree97 첨부드린 레퍼런스 보시면 될 듯 합니다

**Comment by EvergreenTree97** [comment]
저도 과거에 경험했던 방식이기도 하고, android 의존성 없이 usecase di가 가능하여 좋은 방식 같다고 생각합니다
