### ISSUE TITLE
SVG 리소스 필요

### ISSUE THREAD

**Issue by jisungbin** [duckie-team/duckie-android#80]
## 필요한 SVG 리소스

- [x] `img_duckie_talk`
- [x] `img_duckie_intro`

**Comment by EvergreenTree97** [comment]
혜진님께 요청 완료했습니다

**Comment by jisungbin** [comment]
> 혜진님께 요청 완료했습니다

감사합니다 상록님! ❤️

**Comment by jisungbin** [comment]
## DONE
