### ISSUE TITLE
`@Inject` 가 작동하지 않음

### ISSUE THREAD

**Issue by jisungbin** [duckie-team/duckie-android#93]
`:di` 에서 `:feature-ui-onboarding` 으로 Inject 가 정상적으로 진행되지 않음
추후 재시도가 필요함

**Comment by EvergreenTree97** [comment]
[GalleryRepositoryModule](https://github.com/duckie-team/duckie-android/blob/develop/di/src/main/kotlin/team/duckie/app/android/di/repository/GalleryRepositoryModule.kt)의 경우, `SingletonComponent`로 생성하여 ApplicationContext를 주입 받을 수 있음

[KakaoRepositoryModule](https://github.com/duckie-team/duckie-android/blob/develop/di/src/main/kotlin/team/duckie/app/android/di/repository/UserRepositoryModule.kt)의 경우, activityContext를 Data layer에서 주입받을 수 없음

**Comment by jisungbin** [comment]
@EvergreenTree97 탁월한 분석 감사합니다 👍🏼 
`GalleryRepositoryModule` 만 `@Inject` 를 수정하는 쪽으로 하여 PR 가능할까요?
